Revert the docs action as it doesn't work on Windows

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -31,7 +31,17 @@ jobs:
       run: |
         make html
       working-directory: ./docs
-    - name: Deploy to GitHub Pages
-      uses: JamesIves/github-pages-deploy-action@v4
-      with:
-        folder: docs/_build/html
+    - name: Commit & push documentation changes
+      run: |
+        git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin gh-pages
+        git worktree add gh-pages gh-pages
+        git -C gh-pages rm -rf .
+        cp -recurse docs/_build/html/* gh-pages/
+        cd gh-pages
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add .
+        git commit -m "Update documentation to $GITHUB_SHA" || true
+        # The above command will fail if no changes were present, so we ignore
+        # the return code.
+        git push
